version: '2'
services:
  room-assistant:
    image: mkerix/room-assistant:latest-arm32
    restart: always
    network_mode: host
    environment:
      SERVICES: 'mqtt,ble,console'
      ROOM: 'docker-room'
      AUTO_DISCOVERY: true
      MQTT_URL: 'mqtt://192.168.1.200'
      MQTT_REJECT_UNAUTHORIZED: true
